import type { Metadata } from "next";
import { GlobalStyle } from "./styles";
import { Roboto } from "next/font/google";
import Header from "@/components/Header";
import "./style.module.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <GlobalStyle />
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
